project_name: cloudflare-access-grafana

before:
  hooks:
    - go mod download

builds:
- env:
    - CGO_ENABLED=0
  main: ./main.go

  goarch:
    - arm64
    - amd64
  goos:
    - linux

archives:
- replacements: {}
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
